markdown: kramdown
permalink: /:title.html
url: freeblank.github.io
lsi: true
rouge: true
safe: true

# presonal config
title: FreeBlank's Blog
feed: /atom.xml
comments: disqus

author:
  name: frank
  nickname: frank
  email: freeblank.xie@gmail.com
  gmail: freeblank.xie@gmail.com
  qq: http://wpa.qq.com/msgrd?v=3&uin=510732083&site=qq&menu=yes
  site: https://freeblank.github.io/blog

seo:
  keyword:
  description:
