markdown: kramdown
permalink: /:title.html
url: 
lsi: true
#highlighter: rouge
safe: true

highlighter: rouge

kramdown:
  syntax_highlighter: rouge


# presonal config
title: FreeBlank's Blog
subtitle: create infinite bugs with limited life
feed: /atom.xml
comments: disqus

author:
  name: frank
  nickname: frank
  email: freeblank.xie@gmail.com
  gmail: freeblank.xie@gmail.com
  qq: http://wpa.qq.com/msgrd?v=3&uin=510732083&site=qq&menu=yes
  site: https://freeblank.github.io/blog

seo:
  keyword:
  description:
